// This file is auto-generated by Convex after running `npx convex deploy`
// It won't exist until you deploy, but we create this stub so TypeScript doesn't error

export {};

declare global {
  namespace ConvexGenerated {
    type DataModel = {};
  }
}
